name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build and push image
      uses: ./
      env:
        DOCKER_BUILDKIT: 1
      with:
        registry: localhost:5000
        repository: riki2225/build_image
        tags: Build
    
    - name: Run push registry
      run: docker push riki2225/build_image:latest
      
    - name: Run image from registry
      run: docker run localhost:5000/riki2225/build_image:Build
