name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Build and push image
      uses: '../../action.yml'
    - name: Build and push image
      uses: ./
      env:
        DOCKER_BUILDKIT: 1
      with:
        repository: riki2225/build_image
        tags: riki2225/build_image:latest
    
    - name: Run build image
      run: docker build --tag riki2225/build_image:latest
    
    - name: Run image ls
      run: docker image ls
      
    - name: Run push
      run: docker push riki2225/build_image:tagname
